import { headers } from 'next/headers';

import { wagmiConfig } from '~/lib/viem';

import '98.css';
import type { Metadata } from 'next';
import { cookieToInitialState } from 'wagmi';
import { Web3Provider } from '~/providers';
import '~/styles/globals.css';

import { Toaster } from '~/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie')
  );

  return (
    <html lang='en'>
      <body
        style={{
          fontFamily: 'Pixelated MS Sans Serif',
        }}
      >
        <Web3Provider initialState={initialState}>{children}</Web3Provider>
        <Toaster />
      </body>
    </html>
  );
}
